workflows:
  ios-simple:
    name: iOS Simple Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.16.9
      xcode: 15.2
      cocoapods: 1.14.3
    scripts:
      - name: Flutter build
        script: |
          flutter clean
          flutter pub get
          cd ios && pod install && cd ..
          flutter build ios --debug --no-codesign

  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: 3.16.9
    scripts:
      - name: Flutter build
        script: |
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk 